language: python

python:
  - 2.7
  - 3.4
  - 3.5

# https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-a-GUI
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

install:
  - pip install numpy
  - pip install matplotlib
  - pip install iminuit
  - pip install nose
  - pip install sphinx sphinx_rtd_theme

script:
  - python setup.py build_ext -i
  - nosetests
  - cd docs && make html
