language: python

python:
  - 2.7
  - 3.4
  - 3.5

env:
  # Running the tests with and without optional dependencies
  - RUN_TESTS=TRUE INSTALL_OPT_DEPS=TRUE
  - RUN_TESTS=TRUE INSTALL_OPT_DEPS=FALSE
  # Running the linter(s)
  - RUN_LINTERS=TRUE INSTALL_OPT_DEPS=TRUE
  # Building the package with and without optional dependencies
  - BUILD_PACKAGE=TRUE INSTALL_OPT_DEPS=TRUE
  - BUILD_PACKAGE=TRUE INSTALL_OPT_DEPS=FALSE
  # Building the documentation with the optional dependencies
  - BUILD_DOCS=TRUE INSTALL_OPT_DEPS=TRUE

# https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-a-GUI
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

before_install:
  # This command should always succeed, and requires no dependencies
  - python setup.py egg_info

install:
  - ./ci/install.sh

script:
  - ./ci/run.sh
