language: python

python:
  - 2.7
  - 3.4
  - 3.5

env:
  - INSTALL_MATPLOTLIB=TRUE
  - INSTALL_MATPLOTLIB=FALSE

# https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-a-GUI
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

before_install:
  # This command should always succeed, and requires no dependencies
  - python setup.py egg_info

install:
  - pip install Cython
  - pip install numpy
  - if [[ "$INSTALL_MATPLOTLIB" == TRUE ]]; then pip install matplotlib; fi
  - pip install iminuit
  - pip install pytest pytest-cov pytest-mpl
  - pip install flake8 pylint
  # ipython needed for docs: IPython.sphinxext.ipython_directive
  # Can only build the documentation with matplotlib
  - if [[ "$INSTALL_MATPLOTLIB" == TRUE ]]; then pip install ipython sphinx sphinx_rtd_theme; fi

script:
  - make build
  - make flake8
  - make pylint
  - make test
  - if [[ "$INSTALL_MATPLOTLIB" == TRUE ]]; then make doc; fi
